---
- name: Add MongoDB Repository
  yum_repository:
    name: MongoDBRepository
    description: MongoDB.org Repository
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{mongo_version}}/x86_64/
    gpgkey: https://www.mongodb.org/static/pgp/server-{{mongo_version}}.asc
    gpgcheck: yes

- name: Install MongoDB via yum
  yum: name=mongodb-org state=latest

