---
- name: add MongoDB apt key
  apt_key: url=https://www.mongodb.org/static/pgp/server-{{mongo_version}}.asc state=present

- name: add MongoDB repository
  apt_repository: repo='deb http://repo.mongodb.org/apt/debian {{ansible_distribution_release}}/mongodb-org/{{mongo_version}} main' state=present filename='mongodb'

- name: Update APT Cache
  apt: update_cache=yes

- name: Install MongoDB
  apt: pkg=mongodb-org state=present


